# Generated by Django 3.2.3 on 2021-05-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='artist',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='songs',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
