# Generated by Django 3.2.3 on 2021-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0002_auto_20210531_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='img',
            field=models.ImageField(default='JAAN NISAAR.jpg', upload_to='pics'),
        ),
    ]
