# Generated by Django 3.2.3 on 2021-06-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0004_songs_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song',
            field=models.FileField(default='zaalima lofi.mp3', upload_to='audios'),
        ),
    ]
